### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ostrokach** [spyder-ide/conda-manager#5]
Is `conda-manager` working after it was migrated to a standalone package?

---

After chainging the `11th` line in `setup.py` from:

```
with open("conda-manager/__init__.py") as f:
```

to:

```
with open("conda_manager/__init__.py") as f:
```

I was able to install it.

However, running `conda-manager` from the command line, I get the following error:

```
  File "/home/username/anaconda3/bin/conda-manager", line 9, in <module>
    load_entry_point('conda-manager==0.1.0', 'gui_scripts', 'conda-manager')()
  File "/home/username/anaconda3/lib/python3.4/site-packages/setuptools-14.3.1-py3.4.egg/pkg_resources/__init__.py", line 522, in load_entry_point
  File "/home/username/anaconda3/lib/python3.4/site-packages/setuptools-14.3.1-py3.4.egg/pkg_resources/__init__.py", line 2647, in load_entry_point
  File "/home/username/anaconda3/lib/python3.4/site-packages/setuptools-14.3.1-py3.4.egg/pkg_resources/__init__.py", line 2320, in load
  File "/home/username/anaconda3/lib/python3.4/site-packages/setuptools-14.3.1-py3.4.egg/pkg_resources/__init__.py", line 2326, in resolve
  File "/home/username/working/packages/conda-manager/conda_manager/app/__init__.py", line 5, in <module>
    from .main_window import MainWindow
  File "/home/username/working/packages/conda-manager/conda_manager/app/main_window.py", line 1, in <module>
    from qtpy.QtWidgets import QMainWindow
ImportError: No module named 'qtpy'
```

After installing `qtpy` using `pip install qtpy`, I get a different error:

```
Traceback (most recent call last):
  File "/home/username/anaconda3/bin/conda-manager", line 9, in <module>
    load_entry_point('conda-manager==0.1.0', 'gui_scripts', 'conda-manager')()
  File "/home/username/anaconda3/lib/python3.4/site-packages/setuptools-15.0-py3.4.egg/pkg_resources/__init__.py", line 546, in load_entry_point
  File "/home/username/anaconda3/lib/python3.4/site-packages/setuptools-15.0-py3.4.egg/pkg_resources/__init__.py", line 2666, in load_entry_point
  File "/home/username/anaconda3/lib/python3.4/site-packages/setuptools-15.0-py3.4.egg/pkg_resources/__init__.py", line 2339, in load
  File "/home/username/anaconda3/lib/python3.4/site-packages/setuptools-15.0-py3.4.egg/pkg_resources/__init__.py", line 2345, in resolve
  File "/home/username/working/packages/conda-manager/conda_manager/app/__init__.py", line 5, in <module>
    from .main_window import MainWindow
  File "/home/username/working/packages/conda-manager/conda_manager/app/main_window.py", line 3, in <module>
    class MainWindow(QtWidgets.QMainWindow):
NameError: name 'QtWidgets' is not defined
```

Any idea what is missing? And I still don't really understand how I would open `conda-manager` from within Spyder rather than a terminal..?

Thanks a lot for your work!

**Comment by goanpeca** [comment]
The package was migrated, but it is not (yet) operational. Sorry for the inconvenience

**Comment by ccordoba12** [comment]
@ostrokach, just run

```
pip install qtpy
```

to install `qtpy`, a dependency of `conda-manager`.

**Comment by ostrokach** [comment]
@ccordoba12 

Sorry, I had a typo in the original post. I ran `pip install qtpy`, not `pip install pyqt`, to fix the first error. `pyqt` was installed from the start, as it is included in the anaconda distro.

**Comment by ccordoba12** [comment]
@goanpeca, you should change your package's name :-) It's terribly confusing to have `pyqt` and `qtpy`.
